// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTotalAccrualByUserID = `-- name: GetTotalAccrualByUserID :one
SELECT COALESCE(SUM(accrual), 0)::double precision AS total
FROM orders
WHERE user_id = $1 AND status = 'PROCESSED'
`

func (q *Queries) GetTotalAccrualByUserID(ctx context.Context, userID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalAccrualByUserID, userID)
	var total float64
	err := row.Scan(&total)
	return total, err
}
