// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         int64
	UserID     pgtype.UUID
	Number     string
	Status     string
	Accrual    pgtype.Float8
	UploadedAt time.Time
}

type User struct {
	ID           pgtype.UUID
	Login        string
	PasswordHash string
	CreatedAt    time.Time
}

type Withdrawal struct {
	ID          int64
	UserID      pgtype.UUID
	OrderNumber string
	Sum         float64
	ProcessedAt time.Time
}
