// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, number, status, accrual, uploaded_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, number, status, accrual, uploaded_at
`

type CreateOrderParams struct {
	UserID     pgtype.UUID
	Number     string
	Status     string
	Accrual    pgtype.Float8
	UploadedAt time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Number,
		arg.Status,
		arg.Accrual,
		arg.UploadedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Number,
		&i.Status,
		&i.Accrual,
		&i.UploadedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, user_id, number, status, accrual, uploaded_at
FROM orders
WHERE number = $1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, number string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, number)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Number,
		&i.Status,
		&i.Accrual,
		&i.UploadedAt,
	)
	return i, err
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, user_id, number, status, accrual, uploaded_at
FROM orders
WHERE user_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Number,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersPendingAccrual = `-- name: GetOrdersPendingAccrual :many
SELECT id, user_id, number, status, accrual, uploaded_at
FROM orders
WHERE status IN ('NEW', 'PROCESSING')
ORDER BY uploaded_at ASC
`

func (q *Queries) GetOrdersPendingAccrual(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersPendingAccrual)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Number,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderAccrual = `-- name: UpdateOrderAccrual :exec
UPDATE orders
SET status = $2, accrual = $3
WHERE id = $1
`

type UpdateOrderAccrualParams struct {
	ID      int64
	Status  string
	Accrual pgtype.Float8
}

func (q *Queries) UpdateOrderAccrual(ctx context.Context, arg UpdateOrderAccrualParams) error {
	_, err := q.db.Exec(ctx, updateOrderAccrual, arg.ID, arg.Status, arg.Accrual)
	return err
}
