// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error)
	GetOrderByNumber(ctx context.Context, number string) (Order, error)
	GetOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Order, error)
	GetOrdersPendingAccrual(ctx context.Context) ([]Order, error)
	GetTotalAccrualByUserID(ctx context.Context, userID pgtype.UUID) (float64, error)
	GetTotalWithdrawnByUserID(ctx context.Context, userID pgtype.UUID) (float64, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	GetWithdrawalsByUserID(ctx context.Context, userID pgtype.UUID) ([]Withdrawal, error)
	UpdateOrderAccrual(ctx context.Context, arg UpdateOrderAccrualParams) error
}

var _ Querier = (*Queries)(nil)
