// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withdrawals.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (user_id, order_number, sum, processed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, order_number, sum, processed_at
`

type CreateWithdrawalParams struct {
	UserID      pgtype.UUID
	OrderNumber string
	Sum         float64
	ProcessedAt time.Time
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal,
		arg.UserID,
		arg.OrderNumber,
		arg.Sum,
		arg.ProcessedAt,
	)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNumber,
		&i.Sum,
		&i.ProcessedAt,
	)
	return i, err
}

const getTotalWithdrawnByUserID = `-- name: GetTotalWithdrawnByUserID :one
SELECT COALESCE(SUM(sum), 0)::double precision AS total
FROM withdrawals
WHERE user_id = $1
`

func (q *Queries) GetTotalWithdrawnByUserID(ctx context.Context, userID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalWithdrawnByUserID, userID)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const getWithdrawalsByUserID = `-- name: GetWithdrawalsByUserID :many
SELECT id, user_id, order_number, sum, processed_at
FROM withdrawals
WHERE user_id = $1
ORDER BY processed_at DESC
`

func (q *Queries) GetWithdrawalsByUserID(ctx context.Context, userID pgtype.UUID) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, getWithdrawalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Withdrawal
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderNumber,
			&i.Sum,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
